(set-logic BV)

(synth-fun naive_fp32_add ((x (_ BitVec 4)) (y (_ BitVec 4))) (_ BitVec 4)
;declare the nonterminals
((StartBV4 (_ BitVec 4)) (StartBool Bool) (StartBV3 (_ BitVec 3))
    (StartBV2 (_ BitVec 2))(StartBV1 (_ BitVec 1))) 
; production rules that produce BitVec 4
((StartBV4 (_ BitVec 4)  (
    x y ; the parameters
    #b0000 #b1111 ; any constants you want to include
    (bvor StartBV4 StartBV4)
    (bvand StartBV4 StartBV4)
    (bvadd StartBV4 StartBV4)
    (bvsub StartBV4 StartBV4)
    (bvmul StartBV4 StartBV4)
    (bvudiv StartBV4 StartBV4)
    (bvurem StartBV4 StartBV4)
    (bvshl StartBV4 StartBV4)
    (bvlshr StartBV4 StartBV4)
    (bvnot StartBV4)
    (bvneg StartBV4)
    (ite StartBool StartBV4 StartBV4)
    (concat StartBV3 StartBV1)
    (concat StartBV2 StartBV2)
    (concat StartBV1 StartBV3)
    )) 
; production rules for bool
(StartBool Bool (
    (bvugt StartBV4 StartBV4)
    (bvult StartBV4 StartBV4)
    (bvslt StartBV4 StartBV4)
    (bvsle StartBV4 StartBV4)
    (bvugt StartBV3 StartBV3)
    (bvult StartBV3 StartBV3)
    (bvslt StartBV3 StartBV3)
    (bvsle StartBV3 StartBV3)
    (bvugt StartBV2 StartBV2)
    (bvult StartBV2 StartBV2)
    (bvslt StartBV2 StartBV2)
    (bvsle StartBV2 StartBV2)
    (= StartBV4 StartBV4)
    (= StartBV3 StartBV3)
    (= StartBV2 StartBV2)
    (= StartBV1 StartBV1)
    (and StartBool StartBool)
    (or StartBool StartBool)
    (not StartBool)
    (= StartBV1 #b1) ; cast a bv1 into a bool
    ))
; production rules for BitVec 3
(StartBV3 (_ BitVec 3)  (
    #b000 #b111 ; any constants you want to include
    (bvor StartBV3 StartBV3)
    (bvand StartBV3 StartBV3)
    (bvadd StartBV3 StartBV3)
    (bvsub StartBV3 StartBV3)
    (bvmul StartBV3 StartBV3)
    (bvudiv StartBV3 StartBV3)
    (bvurem StartBV3 StartBV3)
    (bvshl StartBV3 StartBV3)
    (bvlshr StartBV3 StartBV3)
    (bvnot StartBV3)
    (bvneg StartBV3)
    (ite StartBool StartBV3 StartBV3)
    (concat StartBV2 StartBV1)
    (concat StartBV1 StartBV2)
    ((_ extract 2 0) StartBV4)
    ((_ extract 3 1) StartBV4)
    )) 
; production rules for BitVec 3
(StartBV2 (_ BitVec 2)  (
    #b00 #b11 ; any constants you want to include
    (bvor StartBV2 StartBV2)
    (bvand StartBV2 StartBV2)
    (bvadd StartBV2 StartBV2)
    (bvsub StartBV2 StartBV2)
    (bvmul StartBV2 StartBV2)
    (bvudiv StartBV2 StartBV2)
    (bvurem StartBV2 StartBV2)
    (bvshl StartBV2 StartBV2)
    (bvlshr StartBV2 StartBV2)
    (bvnot StartBV2)
    (bvneg StartBV2)
    (ite StartBool StartBV2 StartBV2)
    (concat StartBV1 StartBV1)
    ((_ extract 1 0) StartBV4)
    ((_ extract 2 1) StartBV4)
    ((_ extract 3 2) StartBV4)
    ((_ extract 1 0) StartBV3)
    ((_ extract 2 1) StartBV3)
    )) 
; production rules for BitVec 1
(StartBV1 (_ BitVec 1)  (
    #b0 #b1 ; any constants you want to include
    ((_ extract 0 0) StartBV4)
    ((_ extract 1 1) StartBV4)
    ((_ extract 2 2) StartBV4)
    ((_ extract 3 3) StartBV4)
    ((_ extract 0 0) StartBV3)
    ((_ extract 1 1) StartBV3)
    ((_ extract 2 2) StartBV3)
    ((_ extract 0 0) StartBV2)
    ((_ extract 1 1) StartBV2)
    ) 
    ))
)

(declare-var x (_ BitVec 4))
(declare-var y (_ BitVec 4))
(constraint (bvuge (max2 x y) x))
(constraint (bvuge (max2 x y) y))
(constraint (or (= x (max2 x y)) (= y (max2 x y))))

(check-synth)

